apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kms-pvc
  namespace: kms-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
