- name: Add Harbor Helm repository
  become: yes
  become_user: root
  shell: |
    helm repo add harbor https://helm.goharbor.io
    helm repo update
  register: harbor_repo_output

- name: Check if Harbor is already installed
  shell: helm --kubeconfig /etc/rancher/rke2/rke2.yaml list -n default | grep -c harbor
  register: harbor_list_output
  ignore_errors: true
  when: inventory_hostname in groups['masters']

- name: Install Harbor using Helm (if not already installed)
  become: yes
  become_user: root
  shell: |
    helm install harbor harbor/harbor --kubeconfig /etc/rancher/rke2/rke2.yaml
  when:
    - inventory_hostname in groups['masters']
    - harbor_list_output.stdout == "0"

